version: '3.1'

services:

  mysql_db_container:
    image: mysql:8.0.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_TCP_PORT: 3306
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql_db_data:/var/lib/mysql

  adminer_container:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: mysql_db_container
      ADMINER_DEFAULT_DB_NAME: my_db
      ADMINER_DESIGN: galkaev
      ADMINER_PLUGINS: tables-filter tinymce
    restart: always
    ports:
      - 8085:8080
    depends_on:
      - mysql_db_container

  tm_backend_container:
    build:
      context: ./tm-backend
      dockerfile: Dockerfile.dev
    volumes:
      - "./tm-backend/build/libs:/usr/local/tomcat/webapps/"
    expose:
      - 8089
    ports:
      - "8089:8089"
    depends_on:
      - mysql_db_container

  tm_frontend_container:
    build:
      context: ./tm-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "./tm-frontend/build/:/usr/local/tomcat/webapps/"
    expose:
      - 8090
    ports:
      - "8090:8090"
    depends_on:
      - tm_backend_container
volumes:
    mysql_db_data: 